using System;
using System.Collections.Generic;

#nullable disable

namespace datamaster
{
    public partial class Tan
    {
        public int ShsId { get; set; }
        public double? San { get; set; }
        public double? For { get; set; }
        public double? Kha { get; set; }
        public double? Mos { get; set; }
        public double? Hes { get; set; }
        public double? Dar { get; set; }
        public double? Mfo { get; set; }
        public double? Mkh { get; set; }
        public double? Tpa { get; set; }
        public double? Tda { get; set; }
        public double? Apa { get; set; }
        public double? Ada { get; set; }
        public double? Mdg { get; set; }
        public double? Hfo { get; set; }
        public double? Hkh { get; set; }
        public double? Hta { get; set; }
        public double? Hda { get; set; }
        public double? Hko { get; set; }
        public double? Mka { get; set; }
        public double? Mkp { get; set; }
        public bool Cam { get; set; }
        public string Nameco { get; set; }
        public string Adr { get; set; }
        public bool Carm { get; set; }
        public bool Ccode { get; set; }
        public string Code { get; set; }
        public bool Ctram { get; set; }
        public bool Cmhf { get; set; }
        public bool Cmos { get; set; }
        public string Morf { get; set; }
        public short? Cfontsize { get; set; }
        public double? AsTime { get; set; }
        public double? Fontsize { get; set; }
        public short? Ashar { get; set; }
        public string Noezip { get; set; }
        public string Polstring { get; set; }
        public string Noesearch { get; set; }
        public string Noetakh { get; set; }
        public bool ChpSet { get; set; }
        public double? ChpDay { get; set; }
        public double? CodAsli { get; set; }
        public bool Nemahint { get; set; }
        public string Noechap { get; set; }
        public short? Radhigh { get; set; }
        public short? Hashieh { get; set; }
        public short? Hashieh2 { get; set; }
        public short? Hashieh3 { get; set; }
        public short? Hashieh4 { get; set; }
        public bool Radsepar { get; set; }
        public short? Ertfac { get; set; }
        public bool AutoChp { get; set; }
        public string Namezip { get; set; }
        public bool EsName { get; set; }
        public string Lockdate { get; set; }
        public double? Lockcod { get; set; }
        public bool MinmaxW { get; set; }
        public bool Cadr { get; set; }
        public bool Noezar { get; set; }
        public short? MaxFie { get; set; }
        public string SepFie { get; set; }
        public string Noepaper { get; set; }
        public double? WPaper { get; set; }
        public double? HPaper { get; set; }
        public string Mor1 { get; set; }
        public string Mor2 { get; set; }
        public string Mor3 { get; set; }
        public double? Kark { get; set; }
        public string Zippath { get; set; }
        public string TozFac { get; set; }
        public bool ChpTozF { get; set; }
        public double? TarhFac { get; set; }
        public double? TarhSa0 { get; set; }
        public string Autopath { get; set; }
        public bool AsSet { get; set; }
        public string TozSan { get; set; }
        public bool ChpTozS { get; set; }
        public bool OpenSa { get; set; }
        public short? Tedcopyfac { get; set; }
        public bool EditSa2 { get; set; }
        public double? Fasfishhog { get; set; }
        public bool Chpkarb { get; set; }
        public bool Showmanfac { get; set; }
        public bool Autosanoff { get; set; }
        public bool PeyNoecol { get; set; }
        public bool PeyMasdod { get; set; }
        public bool PeyEtebar { get; set; }
        public bool Hideobjfac { get; set; }
        public bool SanfacCal { get; set; }
        public bool SanfacAba { get; set; }
        public bool SanfacTca { get; set; }
        public bool SanfacTfa { get; set; }
        public string FrepTar1 { get; set; }
        public string FrepTar2 { get; set; }
        public bool FacChkKa { get; set; }
        public string FacEmz1 { get; set; }
        public string FacEmz2 { get; set; }
        public string FacEmz3 { get; set; }
        public double? TankhaEt { get; set; }
        public double? Tankha { get; set; }
        public string Mor4 { get; set; }
        public string Mor5 { get; set; }
        public bool TanChap { get; set; }
        public bool NoLine2 { get; set; }
        public bool NoKhoda { get; set; }
        public bool Nosotsepar { get; set; }
        public string FacEmz4 { get; set; }
        public bool ChapMor { get; set; }
        public bool Nodelspace { get; set; }
        public bool Noshog { get; set; }
        public bool SanfacShs { get; set; }
        public bool ChpadrCol { get; set; }
        public bool ChptozCol { get; set; }
        public bool BarcodSel { get; set; }
        public double? TedCP { get; set; }
        public bool TozihCadd { get; set; }
        public string FacLabel { get; set; }
        public bool FaccodSa { get; set; }
        public bool FactarS { get; set; }
        public bool FprnFree { get; set; }
        public bool Nosizecchk { get; set; }
        public double? Vizitor { get; set; }
        public double? SodZian { get; set; }
        public bool Sanfackhad { get; set; }
        public bool ShowtarS { get; set; }
        public bool Noautozip { get; set; }
        public bool Facshoms { get; set; }
        public double? Hkark { get; set; }
        public double? Bem { get; set; }
        public double? Maliat { get; set; }
        public string FfoaLabel { get; set; }
        public double? Bestankarn { get; set; }
        public bool Ffotoplkha { get; set; }
        public short? Asharhog { get; set; }
        public short? Factars1 { get; set; }
        public string TozFta { get; set; }
        public bool ChpTozFt { get; set; }
        public string DbfCb { get; set; }
        public short? Dbffont { get; set; }
        public string TozHog { get; set; }
        public bool ChpTozHo { get; set; }
        public short? TedHcm { get; set; }
        public bool Doprojects { get; set; }
        public string Chapfont { get; set; }
        public byte[] Arm { get; set; }
        public bool? Doshobe { get; set; }
        public bool? Nomoemoj { get; set; }
        public bool? SanfacBar { get; set; }
        public short? Chaptedhcm { get; set; }
        public string FacEmz5 { get; set; }
        public string Displayfnt { get; set; }
        public short? Displayfs { get; set; }
        public bool? Displayfb { get; set; }
        public bool? ShommojAv { get; set; }
        public bool? Groupshom { get; set; }
        public bool? Chapfacviz { get; set; }
        public short? Dovizitor { get; set; }
        public bool? Splitabad { get; set; }
        public bool? Facdbg1 { get; set; }
        public bool? Dofacnagh { get; set; }
        public bool? Docalgroup { get; set; }
        public bool? Dohadfor { get; set; }
        public bool? Chapfacted { get; set; }
        public bool? Chapfaczar { get; set; }
        public bool? Callerid { get; set; }
        public bool? Doserial { get; set; }
        public bool? Tozihtoagl { get; set; }
        public bool? Stretch { get; set; }
        public bool? Wordwrap { get; set; }
        public bool? Ftasankark { get; set; }
        public short? Noechapfac { get; set; }
        public bool? Showmanzar { get; set; }
        public bool? ChpTozPf { get; set; }
        public string TozPfa { get; set; }
        public double? AaCodHc { get; set; }
        public double? AaDar { get; set; }
        public double? AaCodHck { get; set; }
        public double? Casher { get; set; }
        public bool? MojudiCalaDaem { get; set; }
        public bool? ShowCalaHasMoj { get; set; }
        public string ScanPath { get; set; }
        public bool? DoCrm { get; set; }
        public string CrmServer { get; set; }
        public string CrmServerPass { get; set; }
        public int CrmShsId { get; set; }
        public bool? DoSms { get; set; }
        public string PostalCode { get; set; }
        public bool? AutoTablesRefresh { get; set; }
        public string CodeMelli { get; set; }
        public int? UpdateCriteria { get; set; }
        public int? CalendarType { get; set; }

        public virtual SalMaly Shs { get; set; }
    }
}
